version: "3.9"

services:
  web:
    container_name: nextjs-blog
    build:
      context: ./app
    ports:
      - "4000:3000"

    volumes:
      # Monta el proyecto local
      - ./app:/app
      - /app/node_modules

      # Monta la base de datos persistente
      - ./app/data:/app/data
    env_file:
      - ./app/.env
    environment:
      NODE_ENV: production

    command: npm run start
